### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by incore-design** [uriegel/WebWindowNetCore#1]
Hello Uwe,

I just cloned your project and I can't get it to run on my machine (Windows 10). I am getting the following errors:

C:\Program Files\dotnet\sdk\3.1.401\Microsoft.Common.CurrentVersion.targets(4651,5): error MSB3030: Datei "D:\coding\WebWindowNetCore\NativeDependencies\NativeWinWebView.dll" konnte nicht kopiert werden, da die Datei nicht gefunden wurde. [D:\coding\WebWindowNetCore\WebWindowNetCore\WebWindowNetCore.fsproj]
C:\Program Files\dotnet\sdk\3.1.401\Microsoft.Common.CurrentVersion.targets(4651,5): error MSB3030: Datei "D:\coding\WebWindowNetCore\NativeDependencies\NativeWinWebView.so" konnte nicht kopiert werden, da die Datei nicht gefunden wurde. [D:\coding\WebWindowNetCore\WebWindowNetCore\WebWindowNetCore.fsproj]
C:\Program Files\dotnet\sdk\3.1.401\Microsoft.Common.CurrentVersion.targets(4651,5): error MSB3030: Datei "D:\coding\WebWindowNetCore\NativeDependencies\WebView2Loader.dll" konnte nicht kopiert werden, da die Datei nicht gefunden wurde. [D:\coding\WebWindowNetCore\WebWindowNetCore\WebWindowNetCore.fsproj]

Any idea of what I am missing?

Kindest
Christian

**Comment by uriegel** [comment]
Hello Christian,

the project WebWindowNetCore is used to create the nuget package 'WebWindowNetCore', which can be referenced as nuget package in your c# application. So as long as you don't want to change 'WebWindowNetCore', you can add the nuget package 'WebWindowNetCore' to your project and use it.

Kindest
Uwe

**Comment by uriegel** [comment]
Hello Christian,
let me know if you have problems using the nuget package.
Uwe

**Comment by incore-design** [comment]
Thanks for help. Got it working now.

Kindest
Christian
